// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApJY0GOF2xhSPtN405u5U4LJ3bSxqvgs',
    appId: '1:1008550570183:web:67193aaa629c9e4b9036e2',
    messagingSenderId: '1008550570183',
    projectId: 'pic-share-app-by-riverti',
    authDomain: 'pic-share-app-by-riverti.firebaseapp.com',
    storageBucket: 'pic-share-app-by-riverti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQFzoa2_jBn_jhSbsI48hmc3BFzWcIJM',
    appId: '1:1008550570183:android:5888d1be6120fbee9036e2',
    messagingSenderId: '1008550570183',
    projectId: 'pic-share-app-by-riverti',
    storageBucket: 'pic-share-app-by-riverti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoFtDF0I1JE_SsFwE0jmnVqC8IWNPCqnM',
    appId: '1:1008550570183:ios:04fd70fce7d842189036e2',
    messagingSenderId: '1008550570183',
    projectId: 'pic-share-app-by-riverti',
    storageBucket: 'pic-share-app-by-riverti.appspot.com',
    iosClientId: '1008550570183-91nomjj6mh1kav1c5embo8ffm7k50sil.apps.googleusercontent.com',
    iosBundleId: 'com.example.windowsApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoFtDF0I1JE_SsFwE0jmnVqC8IWNPCqnM',
    appId: '1:1008550570183:ios:04fd70fce7d842189036e2',
    messagingSenderId: '1008550570183',
    projectId: 'pic-share-app-by-riverti',
    storageBucket: 'pic-share-app-by-riverti.appspot.com',
    iosClientId: '1008550570183-91nomjj6mh1kav1c5embo8ffm7k50sil.apps.googleusercontent.com',
    iosBundleId: 'com.example.windowsApp2',
  );
}
